name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
   
    - name: Publish
      run: dotnet publish
    
    - name: Create zip
      run: cd /home/runner/work/FrontlineMaidBot/FrontlineMaidBot/FrontlineMaidBot/bin/Debug/net5.0/publish/; zip -r publish.zip .

    - name: Stop service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}  
        script: sudo systemctl stop kestrel-frontline-maid-bot.service

    - name: Clean folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}  
        script: rm -rf /www/frontline-maid-bot/*

    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: "/home/runner/work/FrontlineMaidBot/FrontlineMaidBot/FrontlineMaidBot/bin/Debug/net5.0/publish/publish.zip"
          remote: "/www/frontline-maid-bot/publish.zip"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }} 
          
    - name: unzip
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}  
        script: unzip /www/frontline-maid-bot/publish.zip -d /www/frontline-maid-bot/

    - name: Clean publish
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}  
        script: rm /www/frontline-maid-bot/publish.zip
